### ISSUE TITLE
Feature request v 2.0.0

### ISSUE THREAD

**Issue by CrazyBoy49z** [CrazyBoy49z/iconTV#22]
### **Here is a breakdown of each task:**

 - [ ]  Rewrite to Alpine.js: This task involves replacing the current framework being used with Alpine.js.
 - [ ]  Delete jQuery: This task involves removing jQuery from the project.
 - [ ]  Redesign: This task involves redesigning the project.  Add Tailwind style: This task involves adding Tailwind style to the project.
 - [ ]  Make icon output template: This task involves creating an icon output template for the project.
 - [x] Fix render template on MODX 2.8.4: This task involves fixing a rendering issue on MODX version 2.8.4.
 - [ ]  Add type for rendering #18: This task involves adding a type for rendering to the project with a specific issue number of #18.
 - [ ]  Rewrite SVG parser: This task involves rewriting the SVG parser in the project.
 - [ ]  Add FontAwesome icons to [TiyMCE](https://github.com/modxcms/tinymce-rte/pull/44): This task involves adding FontAwesome icons to TinyMCE, using a [plugin](https://github.com/josh18/TinyMCE-FontAwesome-Plugin ) as an example.
 - [ ] Add FontAwesome icons to ClientConfig: This task involves adding FontAwesome icons to ClientConfig, using a hotel from a specific Github user as an example.
 - [ ]  Fix bug #12: This task involves fixing a specific bug with the issue number of #12.
 - [x]  Fix bug #19: This task involves fixing a specific bug with the issue number of 19.
 - [ ]  Send a PR to MIGX: This task involves sending a pull request to MIGX so that it is possible to connect the TV according to the type and add it to oneself.
